name: Run nilaway

on:
  push:
    branches:
      - master
      - main
    paths:
      - "**"
      - "!docs/**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!docs/**"
      - "!**.md"

jobs:
  nilaway-check:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install nilaway
        run: go install go.uber.org/nilaway/cmd/nilaway@latest

      - name: Run nilaway
        run: nilaway -test=false ./...
